#!/usr/bin/env python3
"""Compatibility wrapper for legacy crypto-api-docs adapters."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from src.adapters.base import DocumentPage, ProductAdapter, register_adapter
from src.utils.config import load_config
from src.utils.path_generator import safe_child_path


@register_adapter("crypto_legacy")
class LegacyCryptoAdapter(ProductAdapter):
    """Run the old exchange crawler under the new product model."""

    def discover(self) -> list[Any]:
        return []

    def extract(self, source: Any) -> DocumentPage:
        raise NotImplementedError("Legacy crypto adapters implement crawl directly.")

    def crawl(self, project_root: str | Path, limit: int | None = None) -> list[Path]:
        project_root = Path(project_root).resolve()
        legacy_exchange = self.config.get("source", {}).get("legacy_exchange") or self.config.get("product")
        if not legacy_exchange:
            raise ValueError(f"Missing source.legacy_exchange for {self.product_id}")

        legacy_config_path = safe_child_path(project_root, f"config/legacy/crypto/{legacy_exchange}.yaml")
        legacy_config = load_config(legacy_config_path)
        legacy_config.setdefault("name", legacy_exchange)
        legacy_config["output"] = {
            "base_dir": "docs/crypto/exchanges",
            "dir_name": legacy_exchange,
        }

        import legacy_crypto.adapters  # noqa: F401 - triggers adapter registration
        from legacy_crypto.adapters.base import get_adapter as get_legacy_adapter

        adapter = get_legacy_adapter(legacy_config)
        concurrency = int(self.config.get("source", {}).get("concurrency", 1))
        languages = self.config.get("source", {}).get("languages")
        adapter.crawl(concurrency=concurrency, limit=limit, languages=languages)

        # New indexes are generated by src.utils.indexer after this method returns.
        docs_dir = self.output_dir(project_root)
        return sorted(docs_dir.glob("**/*.md")) if docs_dir.exists() else []
